pipeline:
  python_syntax_check:
    image: python:2.7
    commands:
      - python -m py_compile lambda_function.py

  build-test:
    image: python:2.7
    commands:
      - apt-get update --yes
      - apt-get install zip --yes
      - ./lambdaPackageCreate.sh
      - ls my_app.zip
