version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.8.2
    container_name: elasticsearch
    environment:
      - cluster.name=webtools-dev-cluster
      - node.name=webtools-node1
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /mnt/docker/logs/elasticsearch:/var/log/elasticsearch
      - /mnt/docker/datas/elasticsearch:/usr/share/elasticsearch/data
  cerebro:
    image: yannart/cerebro:latest
    container_name: cerebro
    ports:
      - 9000:9000
  web:
    image: fpfis/httpd-php:72-wt
    container_name: web
    working_dir: /home/ec2-user/environment
    environment:
      - ALLOWINDEXES=+Indexes
      - ALLOWOVERRIDE=All
      - DOCUMENT_ROOT=/home/ec2-user/environment
      - PHP_DISPLAY_ERRORS=On
      - ENVIRONMENT=dev
      - APACHE_EXTRA_CONF_DIR=/data/conf
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - /mnt/docker/logs/httpd:/var/log
      - /home/ec2-user/environment:/home/ec2-user/environment
      - /home/ec2-user/.config/httpd:/data/conf
      - /mnt/docker/tmp/composer:/cache
    restart: always
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    command: --innodb-file-per-table=1 --innodb-log-file-size=1G --optimizer-switch=condition_fanout_filter=off --query-cache-size=128M --query-cache-limit=16M --collation-server=utf8mb4_general_ci --max-join-size=1000000000 --innodb-buffer-pool-instances=8 --innodb-buffer-pool-size=1G --join-buffer-size=2M --key-buffer-size=64M --net-buffer-length=16384 --read-buffer-size=2M --read-rnd-buffer-size=4M --sort-buffer-size=8M --wait-timeout=2880 --thread-cache-size=64 --max-allowed-packet=32M --group-concat-max-len=1000000 --table-open-cache=22000 --character-set-server=utf8mb4 --long-query-time=10 --slow-query-log=1 --explicit_defaults_for_timestamp=ON
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
      - TZ=Europe/Luxembourg
    ports:
      - 3306:3306
    volumes:
      - /mnt/docker/datas/mysql57:/var/lib/mysql
    restart: always
  memcached:
    image: memcached:1.4.21
    container_name: memcached
    command: memcached -m 64
    ports:
      - 11211:11211
    restart: always
  cypress:
    image: cypress/browsers:chrome67
    container_name: cypress
    working_dir: /home/ec2-user/environment
    volumes:
      - /mnt/docker/tmp/node/cache:/root/.npm
      - /mnt/docker/tmp/node/cypress:/root/.cache
      - /home/ec2-user/environment:/home/ec2-user/environment
    tty: true
    restart: always
  couchdb:
    image: couchdb:2.3.1
    container_name: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    ports:
      - 5984:5984
    volumes:
      - /mnt/docker/datas/couchdb:/opt/couchdb/data
    restart: always
  node:
    image: fpfis/nodejs:10-wt
    container_name: node
    working_dir: /opt/nodejs
    depends_on:
      - web
      - couchdb
    ports:
      - 3000:3000
    volumes:
      - /home/ec2-user/environment/euwebtoolsws:/opt/nodejs
      - /home/ec2-user/environment/euwebtools/rest/html2m:/opt/nodejs/rest/html2m
      - /mnt/docker/logs/node:/var/log
    restart: always
